name: 'test'
author: 'yi_Xu'
description: 'Generate repo list for user or organization.'

branding:
  icon: 'list'
  color: 'yellow'

inputs:
  booleanInput:
    description: >
      Test boolean input.
    required: false
    default: false

runs:
  using: 'node12'
  main: 'dist/index.js'