name: Prepare Release
on:
  push:
    branches:
      - main

env:
  BASE_BRANCH: 'main'
  HEAD_BRANCH: 'prepare-release'

jobs:
  build:
    name: Prepare Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Setup nodejs
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12

      - name: Bump version
        run: |
          npx standard-version --skip.commit --skip.tag
          sed 's/^### \[/## [/' -i CHANGELOG.md
          npx prettier --write CHANGELOG.md  --prose-wrap never --ignore-path ./gitignore

      - name: Get version from package.json
        uses: actions/github-script@v3.1.0
        id: version
        with:
          script: |
            const version = require(`${process.env.GITHUB_WORKSPACE}/package.json`).version;
            core.setOutput('repo', context.repo.repo);
            core.setOutput('version', version);

      - name: Create commit
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "chore(release): :bookmark: release v${{steps.version.outputs.version}}"
          git branch -D ${{ env.HEAD_BRANCH }} || (echo "branch ${{ env.HEAD_BRANCH }} not found" && exit 0)
          git checkout -b ${{ env.HEAD_BRANCH }}
          git push -f "https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git"

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0
        with:
          version: ${{steps.version.outputs.version}}
          path: ./CHANGELOG.md

      - name: Create pull request
        uses: actions/github-script@v3.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: truen 
          user-agent: ${{github.repository}}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: '${{ env.HEAD_BRANCH }}',
              base: '${{ env.BASE_BRANCH }}',
              title: 'chore(release): :bookmark: release v${{steps.version.outputs.version}}',
              body: '${{ steps.changelog_reader.outputs.changes }}',
              maintainer_can_modify: true,
            })

