on:
  workflow_dispatch:
name: test3
jobs:
  run:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2.3.5

    - uses: ./
      with:
        booleanInput: wrong
