on: push
name: test
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Get time
        id: info
        uses: actions/github-script@v3.0.0
        with:
          result-encoding: string
          script: |
            return new Date(Date.now()).toISOString().replace(/[^0-9]/g, "");
      
      - name: echo time
        run: echo {{ steps.info.outputs.result }}