name: 'test for pr'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - index.js

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: get-pull-request
        uses: actions/github-script@v4.1
        with:
          script: |
            const {data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: 15,
            });
            core.info(pullRequest);

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2.0.0

      - name: create-pull-request
        if: ${{ always() }}
        uses: actions/github-script@v4.1
        with:
          script: |
            await github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'prepare-release',
              base: 'main',
              title: 'test create',
              body: `${{ steps.changelog_reader.outputs.changes }}`
            });
      - name: update-pull-request
        if: ${{ always() }}
        uses: actions/github-script@v4.1
        with:
          script: |
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: 15,
              head: 'prepare-release',
              base: 'main',
              title: 'test update title.'
            });

